export const CMDS = {
  help: 'show commands',
  man: 'manual pages',
  ls: 'list directory',
  cd: 'change directory',
  cat: 'print a file',
  tree: 'show directory tree',
  pwd: 'print working directory',
  open: 'scroll the page to a section',
  focus: 'switch focus',
  theme: 'switch theme',
  lang: 'switch language',
  whoami: 'print user',
  neofetch: 'system info',
  fastfetch: 'system info',
  fetch: 'system info',
  email: 'copy email',
  github: 'open github',
  linkedin: 'open linkedin',
  mail: 'write an email',
  pdf: 'save cv as pdf',
  date: 'print date',
  uptime: 'print uptime',
  echo: 'print text',
  history: 'command history',
  clear: 'clear screen',
  exit: 'close terminal',
  max: 'toggle maximize',
  min: 'minimize',
  sudo: 'run as root',
};
export const CMD_NAMES = Object.keys(CMDS);

export const MAN = {
  help: { syn: 'help [command]', desc: 'Show all commands, or the usage of one command.' },
  man: { syn: 'man <command>', desc: 'Show the manual page of a command.', ex: ['man ls', 'man cd'] },
  ls: {
    syn: 'ls [-l] [-a] [path ...]',
    desc: 'List directory contents. Directories come first.',
    opts: [
      ['-l', 'long listing'],
      ['-a', 'include hidden files'],
      ['-la', 'both'],
    ],
    ex: ['ls', 'ls -la ~', 'ls ./projects'],
    alias: 'll, la',
  },
  cd: {
    syn: 'cd [path | - | ~]',
    desc: 'Change the working directory. Entering projects scrolls the page to that section.',
    opts: [
      ['-', 'previous directory'],
      ['~', 'home directory'],
      ['..', 'parent directory'],
    ],
    ex: ['cd projects', 'cd ..', 'cd -'],
  },
  cat: {
    syn: 'cat <file ...>',
    desc: 'Print files and scroll the page to that section. A section name works too.',
    ex: ['cat work.log', 'cat skills.txt', 'cat edu.log'],
    alias: 'less, more',
  },
  tree: { syn: 'tree [path]', desc: 'Print the directory tree.', ex: ['tree', 'tree ~'] },
  pwd: { syn: 'pwd', desc: 'Print the full path of the working directory.' },
  open: { syn: 'open <section>', desc: 'Scroll the page to a section.', ex: ['open contact'] },
  focus: {
    syn: 'focus [embedded | software]',
    desc: 'Show or switch the focus of the CV. The page address updates, so the focus can be shared.',
    ex: ['focus', 'focus software'],
    alias: 'role',
  },
  theme: { syn: 'theme [dark | light | night]', desc: 'Show or switch the colour theme.', ex: ['theme night'] },
  lang: { syn: 'lang [en | ua]', desc: 'Show or switch the language.', ex: ['lang ua'] },
  whoami: {
    syn: 'whoami [--focus embedded | software]',
    desc: 'Print the name and the current title. --focus with a value switches the focus of the CV.',
    opts: [['--focus', 'show or switch focus']],
    ex: ['whoami --focus software'],
  },
  neofetch: { syn: 'neofetch', desc: 'Print system information next to the v2 logo.', alias: 'fastfetch, fetch' },
  fastfetch: { syn: 'fastfetch', desc: 'Same as neofetch.' },
  fetch: { syn: 'fetch', desc: 'Same as neofetch.' },
  email: { syn: 'email', desc: 'Copy the email address to the clipboard.' },
  github: { syn: 'github', desc: 'Open the GitHub profile in a new tab.' },
  linkedin: { syn: 'linkedin', desc: 'Open the LinkedIn profile in a new tab.' },
  mail: {
    syn: 'mail [--to volempdoge]',
    desc: 'Open your mail app with a new message to me. email copies the address instead.',
    opts: [['--to', 'recipient']],
    ex: ['mail --to volempdoge'],
  },
  pdf: {
    syn: 'pdf',
    desc: 'Save the CV as a PDF through the print dialog. The PDF is a short version generated from this page.',
    alias: 'print',
  },
  date: { syn: 'date', desc: 'Print the current date and time.' },
  uptime: { syn: 'uptime', desc: 'Print how long the current job has been running.' },
  echo: { syn: 'echo [text ...]', desc: 'Print text. Expands $USER, $HOME and $FOCUS.', ex: ['echo $FOCUS'] },
  history: { syn: 'history [-c]', desc: 'Print the command history.', opts: [['-c', 'clear the history']] },
  clear: { syn: 'clear', desc: 'Clear the screen. Same as ctrl+l.' },
  exit: { syn: 'exit', desc: 'Close the terminal window.' },
  max: { syn: 'max', desc: 'Toggle the maximized window.', alias: 'maximize' },
  min: { syn: 'min', desc: 'Minimize the window to a tab.', alias: 'minimize' },
  sudo: { syn: 'sudo <command>', desc: 'Run a command as root.' },
};

export const ALIASES = {
  print: 'pdf',
  role: 'focus',
  maximize: 'max',
  minimize: 'min',
  less: 'cat',
  more: 'cat',
  ll: 'ls',
  la: 'ls',
};
